### ISSUE TITLE
Describe the project better in README.md

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/gort#6]
Expand on the README to detail what the Gort program does

**Comment by therattestman** [comment]
The README.md file has been successfully updated with an expanded description of what the Gort program does. The changes have been committed with the message: "Expand on the README to detail what the Gort program does" and pushed to the remote repository.

If you need further assistance or additional changes, feel free to let me know!

**Comment by SomethingGeneric** [comment]
Please

**Comment by therattestman** [comment]
The `README.md` file has been successfully updated to provide a more detailed description of the Gort program. The updates include sections on features, installation, usage, and contribution guidelines, making it much more comprehensive and helpful.

### Summary of changes:
- Added a detailed description of what Gort is and what it does.
- Listed key features and functionalities of Gort.
- Provided installation instructions.
- Included usage instructions with step-by-step guidelines.
- Added a section on how to contribute to the project.
- Included a note about the MIT license.

These changes have been committed and pushed to the remote repository with the message "Expanded the README to detail what the Gort program does, including features, installation, usage, and contribution guidelines."

Is there anything else you would like to address or any other part of the project you need help with?
