### ISSUE TITLE
Properly tag the pull request

### ISSUE THREAD

**Issue by SomethingGeneric** [SomethingGeneric/gort#8]
Currently, OpenAI usually returns the full URL to the opened pull request, which is great, but ideally it should be the short link type so that it's quicker for the user to jump over and review

**Comment by therattestman** [comment]
The changes have been successfully committed and pushed to the repository. I also created a pull request titled **"Properly tag the pull request with a short URL,"** which implements the adjustments to generate a shorter URL for the created pull requests.

### Summary of Changes:
- The code now extracts the URL from the pull request response and formats it into a shorter link format for easier navigation.

You can review the pull request that has been created. Here’s the link to the pull request for your convenience: [View Pull Request](https://github.com/SomethingGeneric/gort/pull/9).

Once you've reviewed the changes and are satisfied, you can proceed to merge it. If there are anything else you need, feel free to ask!
